# <div style="text-align:center"> 1η Εργασία: Τα βασικά της μηχανικής μάθησης </div>

#### <div style="text-align:center">  Παναγιώτοπουλος Γεώργιος **1115201700113** </div>

### <a href="#Ask1"><div style="text-align:center"> [Ερώτημα 1: Πράξεις με Διανύσματα και Πίνακες] </div></a>
Η εξοικείωση με το λογισμό διανυσμάτων και πινάκων είναι απαραίτητη για την κατανόηση 
και την υλοποίηση αλγορίθμων μηχανικής μάθησης.<br> Για το σκοπό αυτό, καλείστε να 
απαντήσετε στα παρακάτω ερωτήματα.<br> Χρησιμοποιώντας το πακέτο random της NumPy να δημιουργήσετε: <br>
* Δύο τυχαίους πίνακες ακέραιων αριθμών $X \in Z^{3\times4}$ και $Y \in Z^{4\times3}$ <br>
* Δύο τυχαία διανύσματα ακέραιων αριθμών $a \in Z^{4}$ και $b \in Z^{4}$ <br>

In [33]:
import numpy as np

In [40]:
#Just for documentation purposes
#np.random.seed(113)
# X = np.random.randint(10,size=(3,4))
# Y = np.random.randint(10,size=(4,3))
# a = np.random.randint(10,size=(4))
# b = np.random.randint(10,size=(4))

In [35]:
X = np.array([[5, 7, 8, 9],
              [7, 7, 1, 1],
              [9, 7, 4, 7]])

Y = np.array([[0, 7, 5],
              [3, 9, 5],
              [4, 3, 1],
              [7, 5, 5]])

a = np.array([4, 4, 7, 6])

b = np.array([4, 6, 6, 4])


 ###  <div style="text-align:center"> Οι τυχαίοι πίνακες και διανύσματα </div>
$$
X = 
\begin{bmatrix}
5 & 7 & 8 & 9 \\
7 & 7 & 1 & 1 \\
9 & 7 & 4 & 7 \\
\end{bmatrix}
$$

$$
Y=\begin{bmatrix}
0 & 7 & 5 \\
3 & 9 & 5 \\
4 & 3 & 1 \\
7 & 5 & 5 \\
\end{bmatrix}
$$

$$
a =\begin{bmatrix}
4 & 4 & 7 & 6
\end{bmatrix}
$$

$$
b=\begin{bmatrix}
4 & 6 & 6 & 4
\end{bmatrix}
$$


###  <a id="Ask1">[Ερώτημα 1]</a>
<a href="#1.1">1.1</a> Να υπολογίσετε το εσωτερικό γινόμενο των διανυσμάτων $a$ και $b$, δηλαδή $a^{T}b$ <br>
<a href="#1.2">1.2</a> Να υπολογίσετε το γινόμενο πίνακα-διανύσματος $Xa \in Z^{3}$ <br>
<a href="#1.3">1.3</a> Να υπολογίσετε το γινόμενο πινάκων $XY \in Z^{3\times3}$ <br>
<a href="#1.4">1.4</a> Να υπολογίσετε την Ευκλείδεια νόρμα (l2-norm) του διανύσματος $a$ <br>
Στις παραπάνω ερωτήσεις καλείστε να εκτελέστε τους υπολογισμούς αναλυτικά βήμα προς 
βήμα με το χέρι, παραθέτοντας όλα τα ενδιάμεσα βήματα και να επιβεβαιώστε τα 
αποτελέσματα με τη χρήση της NumPy. 

<a id = "1.1">1.1</a> <br>
$$
a^{T} b = 
\begin{bmatrix}
4 \\ 4 \\ 7 \\ 6 
\end{bmatrix} *
\begin{bmatrix}
4 & 6 & 6 & 4
\end{bmatrix} = 4*4 + 4*6 + 7*6 + 4*6 = 16 + 24 + 42 + 24 = 106
$$
![1.1](https://i.imgur.com/VTneP6d.png)

In [36]:
result1_1 = np.dot(a,b)
print(result1_1)

106


<a id = "1.2">1.2</a> <br>
<div style="text-align:center"> Θα πολλαπλασιάσουμε με το transpose του $a$,<br> λογώ του τρόπου που ορίσαμε τα διανύσματα: </div>
$$
X a^{T} = \begin{bmatrix}
5 & 7 & 8 & 9 \\
7 & 7 & 1 & 1 \\
9 & 7 & 4 & 7 \\
\end{bmatrix} * 
\begin{bmatrix}
4 \\ 4 \\ 7 \\ 6
\end{bmatrix} = 
\begin{bmatrix}
5*4 + 7*4 + 8*7 + 9*6 \\
7*4 + 7*4 + 1*7 + 1*6 \\
9*4 + 7*4 + 4*7 + 7*6 \\
\end{bmatrix} =
\begin{bmatrix}
20 + 28 + 56 + 56 \\
28 + 28 + 7 + 6 \\
36 + 28 + 28 + 42 \\
\end{bmatrix} =
\begin{bmatrix}
158 \\
69 \\
134 \\
\end{bmatrix}
$$ 

![1.2](https://i.imgur.com/kC264nu.png)

In [37]:
result1_2 = np.dot(X,a)
print(result1_2)

[158  69 134]


<a id = "1.3">1.3</a>
$$
X Y = \begin{bmatrix}
5 & 7 & 8 & 9 \\
7 & 7 & 1 & 1 \\
9 & 7 & 4 & 7 \\
\end{bmatrix} *
\begin{bmatrix}
0 & 7 & 5 \\
3 & 9 & 5 \\
4 & 3 & 1 \\
7 & 5 & 5 \\
\end{bmatrix}
$$

![1.3](https://i.imgur.com/FN68urd.jpg)

In [38]:
result1_3 = np.dot(X,Y)
print(result1_3)

[[116 167 113]
 [ 32 120  76]
 [ 86 173 119]]


<a id = "1.4">1.4</a>
$$
||a||_{2} = \sqrt{(4^{2}+4^{2}+7^{2}+6^{2})} = \sqrt{16 + 16 + 49 + 36} = \sqrt{117} \approx 10.816653
$$
![1.4](https://i.imgur.com/JHXQpDf.jpg)

In [39]:
result1_4 = np.linalg.norm(a, ord=2)
print(result1_4)

10.816653826391969


### <div style="text-align:center"> [Ερώτημα 2: Υπολογισμός παραγώγων]  </div>
<a href="#2.1">2.1</a> Έστω $f(x) = x^{T}Ax + b^{T}x$ , μια συνάρτηση d μεταβλητών, με A συμμετρικό πίνακα (δηλ. $ A = A^{T}$) διάστασης d x d, και $b \in \mathbb{R}^{d}$ . Να υπολογίσετε αναλυτικά βήμα προς βήμα με το χέρι,
την παράγωγο της $f(x)$ ως προς το διάνυσμα $x \in \mathbb{R}^{d}$ παραθέτωντας όλα τα ενδιάμεσα βήματα. <br>
Υπενθιμίζεται ότι η παράγωγος μιας συνάρτησης $f:\mathbb{R}^{d} → \mathbb{R}, \nabla f(x)$ ως προς το διάνυσμα $x \in \mathbb{R}^{d}$ είναι:
$$ \nabla f(x) = \begin{bmatrix}
\frac{\partial f(x)}{\partial x_1} \\
.\\.\\.\\
\frac{\partial f(x)}{\partial x_d}
\end{bmatrix} \in \mathbb{R}^{d} $$ <br>

<a href="#2.2">2.2</a> Έστω Α, Β, Χ πίνακες πραγματικών αριθμών διάστασης d x d με τάξη (rank) ίση με d. Nα βρείτε, αναλυτικά και σε κλειστή μορφή (closed form solution) το ολικό ελάχιστο του 
παρακάτω προβλήματος βελτιστοποίησης: <br>
$$ min_{x} ||A - XB||^{2}_{F}$$
Να εξηγήσετε με λεπτομέρεια όλη τη διαδικασία σκέψης που θα ακολουθήσετε και να 
παραθέσετε όλα τα ενδιάμεσα βήματα των πράξεων.

### <div style="text-align:center"> [Ερώτημα 3: Gradient descent]  </div>
Ο αλγόριθμος gradient descent είναι η πιο διαδεδομένη μέθοδος βελτιστοποίησης στη 
μηχανική μάθηση. Σε αυτό το ερώτημα καλείστε να υλοποιήσετε σε Python τον αλγόριθμο 
gradient descent για την ελαχιστοποίηση συναρτήσεων δύο μεταβλητών.
Θεωρήστε τις παρακάτω συναρτήσεις:
$f_{1}([x_{1},x_{2}]^{T}) = f_{1}(x_{1},x_{2}) = (x_{1} - 2)^{2} + (x_{2} - 3)^{2}$
$f_{2}([x_{1},x_{2}]^{T}) = f_{2}(x_{1},x_{2}) = (1 - (x_{2} - 3))^{2} + 20 ((x_{1}+3) - (x_{2} - 3)^{2})^{2}$ <br>
Nα υλοποιήσετε σε Python και να εκτελέστε τον αλγόριθμο gradient descent για κάθε 
συνάρτηση. <br>
Να αρχικοποιήσετε τις μεταβλητές με μηδέν. Πρώτα, τρέξτε με ένα σταθερό ποσοστό 
εκμάθησης (learning rate) ίσο με 0.5. Να εκτελέστε Τ=10 επαναλήψεις και αναφέρετε την 
τιμή της συνάρτησης στο τέλος κάθε βήματος (επανάληψης). Χρησιμοποιώντας τη matplotlib
να σχεδιάσετε γραφήματα (ένα για κάθε συνάρτηση) που να απεικονίζουν την τιμή της 
συνάρτησης (κάθετος άξονας) ως συνάρτηση των επαναλήψεων (οριζόντιος άξονας). <br>
Στη συνέχεια, να επαναλάβετε τη διαδικασία για διαφορετικές τιμές του learning rate και 
του πλήθους επαναλήψεων (Τ) και αναφέρετε τα αποτελέσματά σας με τη μορφή 
γραφημάτων όπως στο παραπάνω σκέλος του ερωτήματος. <br>
* Πόσες επαναλήψεις χρειάζεται ο αλγόριθμος για να συγκλίνει σε στάσιμο σημείο για 
διαφορετικές τιμές του learning rate για κάθε συνάρτηση;
* Τι συμβαίνει για μεγάλες τιμές του learning rate; 
* Τι συμβαίνει για μικρές τιμές του learning rate;
* Τι συμβαίνει αν χρησιμοποιήσετε διαφορετικές τιμές αρχικοποίησης των 
μεταβλητών;